[parquet_to_minio.destination.filesystem]
bucket_url = "s3://bronze"

[parquet_to_minio.destination.filesystem.credentials]
aws_access_key_id = "admin"
aws_secret_access_key = "password"
endpoint_url = "http://minio:9000"