FROM jupyter/pyspark-notebook

# Instala todos los paquetes necesarios en tiempo de build
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==5.3.2 \
    apache-airflow-providers-openlineage==2.7.0 \
    pandas==2.3.2 \
    "dlt[filesystem]==1.4.0" \
    s3fs==2024.3.1 \
    fsspec==2024.3.1 \
    adlfs \
    pyarrow==21.0.0